### PR TITLE
add deploymentannotations and bump chart version

### PR DESCRIPTION
**Pull request by carpenike**
Enables the use of operators that trigger off of deployment annotations, IE: Stash, istio, etc.

Signed-off-by: Ryan Holt <ryan@ryanholt.net>

### CODE REVIEW

**Review by halkeye — APPROVED** [review]
Looks good. You can always use tojson btw

**Comment by carpenike** [comment]
Nice, haven't done that before. Do you have an example you could point me to?

**Comment by carpenike** [comment]
also, we've got a small group together of folks doing k8s for home services / at home. You're welcome to come hangout. https://discord.gg/vNh55k

**Comment by halkeye** [comment]
I took too long to click the link, i think it was only good for 24 hours, feel free to invite halkeye#1337

**Pull request merged**
