### PR TITLE
support podannotations in deployment

### PR DESCRIPTION
**Pull request by carpenike**
I use Velero for backup and it requires podannotations to find the containers to backup.

### CODE REVIEW

**Review by halkeye — APPROVED** [review]
oooo thx

**Comment by halkeye** [comment]
oh no!

[ERROR] templates/: parse error in "nzbhydra2/templates/deployment.yaml": template: nzbhydra2/templates/deployment.yaml:25: unexpected {{end}}

**Comment by carpenike** [comment]
ah, one second let me fix that.

**Comment by halkeye** [comment]
2.9.4 is pushed

**Comment by halkeye** [comment]
I can't remember if https://jenkins.gavinmogan.com/job/github_orgs/job/halkeye-helm-charts/job/nzbhydra2-chart/job/master/26/console is public

**Comment by carpenike** [comment]
Resolved by #2

**Pull request merged**
